Новичков Борис 924
fivol/NoteManager pull request #1
Opened 2020-05-14 12:13 UTC by fivol

2020-05-19 12:03 UTC, tardis-forever requested changes

2020-05-19 12:03 UTC, tardis-forever commented on client/client.py
> +    parser.add_argument('-p', '--port', default='8000', type=int)
Здесь 8000 точно должно быть в кавычках?

2020-05-19 12:03 UTC, tardis-forever commented on client/client.py
> +        print(SCRIPT_EXIT)
В этот момент можно спросить пользователя, действительно ли он хочет выйти

2020-05-19 12:03 UTC, tardis-forever commented on client/client.py
> +        if not note_id:
На `None` принято проверять явно

2020-05-19 12:03 UTC, tardis-forever commented on client/client.py
> +            print('Введиде команду: ', end='')
Опечатка

2020-05-19 12:03 UTC, tardis-forever commented on client/client.py
> +    quit = exit
Это где-то используется?

2020-05-19 12:04 UTC, tardis-forever commented
8000 стоит вынести в константу

2020-05-22 12:25 UTC, tardis-forever requested changes

2020-05-22 12:25 UTC, tardis-forever commented on client/client.py
> +            if response['status'] == 'fail':
'fail' константа

2020-05-22 12:25 UTC, tardis-forever commented on client/client.py
> +                print('Получен невалидный ответ от сервера')
Строковая константа

2020-05-22 12:25 UTC, tardis-forever commented on client/client.py
> +            print('Введите команду: ', end='')
И тут тоже

2020-05-22 12:25 UTC, tardis-forever commented on client/client.py
> +            command_items = input().split()
Это вроде можно заменить на `input('Введите команду').split()`

2020-05-22 12:25 UTC, tardis-forever commented on server/database.py
> +
2 пустых строки после импортов

2020-05-22 12:25 UTC, tardis-forever commented on server/server.py
> +    parser.add_argument('--port', default=8000, type=int)
Константы

2020-05-22 12:25 UTC, tardis-forever commented on server/server.py
> +app.add_url_rule('/note/<int:note_id>/', view_func=note_view, methods=['GET', 'DELETE'])
Все пути тоже стоит вынести в файл и использовать одно и те же константы и на сервере, а в клиенте

2020-05-22 21:14 UTC, tardis-forever requested changes

2020-05-22 21:14 UTC, tardis-forever commented on client/client.py
> +            if response['status'] == 'fail':
Ну так-то не понятно, почему resolve

2020-05-22 21:14 UTC, tardis-forever commented on server/net_consts.py
> +MANY_NOTES_PATH = '/notes/'
Не надо дублировать переменные, они должны быть общими

2020-05-22 21:15 UTC, tardis-forever commented
Также, непонятно, почему есть пустой server/consts.py

2020-05-23 10:55 UTC, fivol commented on client/client.py
> +            if response['status'] == 'fail':
Просто не залил последнии изменения

2020-05-24 09:59 UTC, tardis-forever commented
Зачтено

2020-05-24 10:00 UTC, tardis-forever commented
Я правильно понимаю, что бонусных баллов здесь нет?

2020-05-24 10:00 UTC, merged